# Generated by Django 4.2.7 on 2024-01-07 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_profile_photo"),
        ("playground", "0003_alter_listing_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="brand",
            field=models.CharField(
                choices=[
                    ("bmw", "BMW"),
                    ("mercedes benz", "Mercedes Benz"),
                    ("audi", "Audi"),
                    ("dodge", "Dodge"),
                    ("subaru", "Subaru"),
                    ("tesla", "Tesla"),
                    ("jaguar", "Jaguar"),
                    ("land rover", "Land Rover"),
                    ("bentley", "Bentley"),
                    ("bugatti", "Bugatti"),
                    ("ferrari", "Ferrari"),
                    ("lamborghini", "Lamborghini"),
                    ("honda", "Honda"),
                    ("toyota", "Toyota"),
                    ("chevrolet", "Chevrolet"),
                    ("porsche", "Porsche"),
                    ("lexuse", "Lexuse"),
                ],
                default=None,
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="LikeListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("like_date", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="playground.listing",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.profile"
                    ),
                ),
            ],
        ),
    ]
